### ISSUE TITLE
A tiny bug?

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft-Localization#284]
![2015-03-11_17 23 16](https://cloud.githubusercontent.com/assets/7806504/6609782/70ea5eb6-c813-11e4-9ffd-0860f2fef54f.png)

**Comment by CovertJaguar** [comment]
Closed by https://github.com/CovertJaguar/Railcraft/commit/27c782cf7784ea2ef4008483b420cd5ea3266ca1
