### ISSUE TITLE
Zinc needs a localization

### ISSUE THREAD

**Issue by liach** [CovertJaguar/Railcraft-Localization#334]
Ping @Generalcamo who added zinc.
![2017-06-06_10 49 46](https://user-images.githubusercontent.com/7806504/26843705-fff0c96c-4aa5-11e7-9d59-3c8bfc160f10.png)

**Comment by 3TUSK** [comment]
Why not go ahead to fix this in languages files that other than`en_us`.

**Comment by liach** [comment]
Too lazy. You can do if you want.
